version: '3.9'

services:

  postfix:
    container_name: ${POSTFIX_NAME}
    build:
      context: ./${POSTFIX_TAG}
    ports:
      - 25
      - 587
    #https://stackoverflow.com/a/38306666/3929620
    extra_hosts:
      - 'localhost.localdomain:127.0.0.1'
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - default
    volumes:
      - ${PWD}/conf:/etc/postfix/conf
      - ${PWD}/certs:/etc/postfix/certs
      - ${PWD}/dkim:/etc/opendkim/domainkeys
    environment:
      maildomain: ${POSTFIX_MAILDOMAIN}
      smtp_user: ${POSTFIX_SMTP_USER}
      dkimselector: ${POSTFIX_DKIMSELECTOR}
      DOMAINS: ${POSTFIX_DOMAINS}
      SRS_DOMAIN: ${SRS_DOMAIN}
      SRS_SENDER_CLASSES: ${SRS_SENDER_CLASSES}
      SRS_EXCLUDE_DOMAINS: ${SRS_EXCLUDE_DOMAINS}
